import { redirect, notFound } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { roundStandings } from '@/lib/scoring'

export const dynamic = 'force-dynamic'

/** Print-ready. The customer uses the browser's Print dialog and saves as PDF. */
export default async function ExportPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  const supabase = await createClient()

  const { data: { user } } = await supabase.auth.getUser()
  if (!user) redirect('/login')

  const { data: event } = await supabase.from('events').select('*').eq('id', id).single()
  if (!event) notFound()

  const { data: rounds } = await supabase
    .from('rounds').select('*').eq('event_id', id).order('position')
  const { data: judges } = await supabase
    .from('judges').select('id, name, position').eq('event_id', id).eq('status', 'active').order('position')

  const perRound = []
  for (const r of rounds ?? []) {
    const standings = await roundStandings(supabase, r.id)
    const { data: cats } = await supabase
      .from('categories').select('name, max_score').eq('round_id', r.id).order('position')
    const { data: entries } = await supabase.from('entries').select('id').eq('round_id', r.id)
    const { data: notes } = await supabase
      .from('entry_comments')
      .select('body, judge_id, entries(contestants(name))')
      .in('entry_id', (entries ?? []).map((e) => e.id))
    perRound.push({ round: r, standings, cats: cats ?? [], notes: notes ?? [] })
  }

  const final = (rounds ?? []).find((r) => !r.advance_count) ?? (rounds ?? [])[rounds!.length - 1]
  const podium = perRound.find((p) => p.round.id === final?.id)?.standings.slice(0, event.winners_count ?? 3) ?? []
  const judgeName = new Map((judges ?? []).map((j) => [j.id, j.name]))

  return (
    <div className="sheetpage">
      <div className="noprint printbar">
        <a className="btn btn-quiet" href={'/events/' + id + '/live'}>Back</a>
        <span className="sub" style={{ margin: 0 }}>Use your browser&rsquo;s Print, then Save as PDF</span>
      </div>

      <article className="paper">
        <header className="paper-head">
          <h1>{event.name}</h1>
          <p>
            {event.event_date ?? 'No date'}{event.venue ? ' \u00B7 ' + event.venue : ''}
            {' \u00B7 '}{judges?.length ?? 0} judge{judges?.length === 1 ? '' : 's'}
          </p>
        </header>

        <section className="paper-block">
          <h2>Result</h2>
          <table>
            <thead><tr><th>Place</th><th>Chest</th><th>Name</th><th>Score</th></tr></thead>
            <tbody>
              {podium.map((s, i) => (
                <tr key={s.entryId}>
                  <td>{i + 1}</td><td>{s.bib ?? ''}</td><td>{s.name}</td><td>{s.score.toFixed(1)}%</td>
                </tr>
              ))}
            </tbody>
          </table>
        </section>

        {perRound.map(({ round, standings, cats, notes }) => (
          <section key={round.id} className="paper-block">
            <h2>Round {round.position} &mdash; {round.name}</h2>
            <p className="paper-note">
              {cats.map((c) => c.name + ' (' + c.max_score + ')').join(' \u00B7 ')}
              {round.advance_count ? ' \u00B7 top ' + round.advance_count + ' advanced' : ' \u00B7 final round'}
            </p>
            <table>
              <thead><tr><th>#</th><th>Chest</th><th>Name</th><th>Judges</th><th>Score</th></tr></thead>
              <tbody>
                {standings.map((s, i) => (
                  <tr key={s.entryId} className={round.advance_count && i < round.advance_count ? 'through' : ''}>
                    <td>{i + 1}</td><td>{s.bib ?? ''}</td><td>{s.name}</td>
                    <td>{s.judgesIn}</td><td>{s.score.toFixed(1)}%</td>
                  </tr>
                ))}
              </tbody>
            </table>

            {notes.filter((n) => n.body).length > 0 && (
              <div className="paper-notes">
                <h3>Judge comments</h3>
                {notes.filter((n) => n.body).map((n, i) => {
                  const who = judgeName.get(n.judge_id) ?? 'Judge'
                  const e = n.entries as unknown as { contestants: { name: string } } | null
                  return <p key={i}><strong>{e?.contestants?.name ?? ''}</strong> &mdash; {who}: {n.body}</p>
                })}
              </div>
            )}
          </section>
        ))}

        <footer className="paper-foot">
          Generated by EventScore &middot; {new Date().toLocaleString('en-IE')}
        </footer>
      </article>
    </div>
  )
}
